Target: test
test: Cell.cpp Cell.h AbstractHex.cpp AbstractHex.h HexVector.cpp HexVector.h HexArray1D.cpp HexArray1D.h HexAdapter.cpp HexAdapter.h driver.cpp 
	g++ -std=c++11 driver.cpp Cell.cpp AbstractHex.cpp HexVector.cpp HexArray1D.cpp HexAdapter.cpp -o output
	./output